controller:
  ros__parameters:
    NX: 7  # length of state vector: z = [x, y, delta, v, yaw, yaw rate, beta]
    NXK: 4  # length of kinematic state vector: z = [x, y, v, yaw]
    NU: 2  # length of input vector: u = = [steering speed, acceleration]
    T: 40  # finite time horizon length
    TK: 8  # finite time horizon length kinematic
    R: [1.0, 0.01]  # input cost matrix, penalty for inputs - [steering_speed, accel]
    Rd: [0.5, 0.01] # input difference cost matrix, penalty for change of inputs - [steering_speed, accel]
    Q: [22.0, 22.0, 0.0, 5.0, 10.0, 0.0, 0.0] # state error cost matrix, for the the next (T) prediction time steps [x, y, delta, v, yaw, yaw-rate, beta]
    Qf: [32.0, 32.0, 0.0, 5.0, 10.0, 0.0, 0.0] # final state error matrix, penalty  for the final state constraints: [x, y, delta, v, yaw, yaw-rate, beta]
    Rk: [0.01, 1.0] # input cost matrix, penalty for inputs - [accel, steering_speed]
    Rdk: [0.01, 0.5] # input difference cost matrix, penalty for change of inputs - [accel, steering_speed]
    Qk: [5.0, 5.0, 5.5, 13.0] # state error cost matrix, for the the next (T) prediction time steps [x, y, delta, v, yaw, yaw-rate, beta]
    Qfk: [5.0, 5.0, 5.5, 13.0] # final state error matrix, penalty  for the final state constraints: [x, y, delta, v, yaw, yaw-rate, beta]
    N_IND_SEARCH: 20  # Search index number
    DT: 0.025  # time step [s]
    DTK: 0.1  # time step [s] kinematic
    dl: 0.03  # dist step [m]
    dlk: 0.03  # dist step [m] kinematic

    LENGTH: 0.58  # Length of the vehicle [m]
    WIDTH: 0.2032  # Width of the vehicle [m]
    WB: 0.33  # Wheelbase [m]
    MIN_STEER: 0.4189  # maximum steering angle [rad]
    MAX_STEER: 0.4189  # maximum steering angle [rad]
    MAX_DSTEER: 3.14159  # maximum steering speed [rad/s]
    MAX_STEER_V: 3.2  # maximum steering speed [rad/s]
    MAX_SPEED: 8.0  # maximum speed [m/s]
    MIN_SPEED: 0.0  # minimum backward speed [m/s]
    MAX_ACCEL: 2.5  # maximum acceleration [m/ss]
    V_KS: 2.0  # switching velocity from kinematic to dynamic [m/s]